name: CMakeBuild and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get -y install libtbb-dev
        
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      run: cmake --build ${{github.workspace}}/build -j

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest
